### ISSUE TITLE
Add dependencies to the Readme instructions

### ISSUE THREAD

**Issue by Lyamc** [4nickel/flink#2]
Could you add the dependencies to the Readme?

```
# Install dependencies for diesel-cli and flink
sudo apt update
sudo apt install build-essential libsqlite3-dev
sudo apt install git ruby
# Install diesel-cli
cargo install diesel_cli --force --no-default-features --features sqlite
# Install compass
gem install compass
# Export Diesel Variable
export DATABASE_URL="sqlite:///tmp/database.sql"
# Install flink
cd flink
make
make server
```

Also this doesn't seem to build.... so rip?

**Comment by 4nickel** [comment]
I updated the code to remove the deprecated syntax and also improved the README as it was missing the toolchain and environment setup.

The dependencies are listed, but installing them depends on your package manager so I can't give detailed instructions.
